# playbook to install chocolatey client
---
- hosts: contoso
  gather_facts: false
  
  collections:
    - chocolatey.chocolatey
    - ansible.windows

  tasks:
    - name: Ensure Chocolatey installed from internal repo
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey
        source: 'http://azeutlart01:8082/artifactory/TylerRepoGeneric/ChocolateyInstall.ps1'
